services:

  db: 
    image: postgres
    restart: always
    # volumes:
    #   - mm_website_pgdata:/var/lib/postgresql/data
    ports:
      - 7777:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}

