services:

  webapp:
    build: 
      context: webapp
      target: dev
    restart: unless-stopped
    ports:
      - "8082:5173"
    volumes:
      - ./webapp:/app
      - /app/node_modules
    depends_on:
      - "db"
      - "nest"
    command: npm run dev

  nest:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    ports:
      - "8081:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - "db"
    command: npm run start:dev

  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}

