import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * This was generated by the migration tool and will be used
 * to apply the scema to the db
 */

export class Init1730653412087 implements MigrationInterface {
  name = 'Init1730653412087';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "todo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" character varying, "author" character varying NOT NULL DEFAULT 'John Doe', "completed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d429b7114371f6a35c5cb4776a7" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "todo"`);
  }
}
