FROM node:18-alpine as dev

WORKDIR /app

ENV NODE_ENV development

RUN addgroup --system --gid 1001 node || true
RUN adduser --system --uid 1001 node || true

COPY --chown=node:node . .

RUN npm install

USER node

# ------

FROM node:18-alpine as build

WORKDIR /app

ENV NODE_ENV production

RUN addgroup --system --gid 1001 node || true
RUN adduser --system --uid 1001 node || true

COPY --chown=node:node --from=dev /app/node_modules ./node_modules

COPY --chown=node:node . .

RUN npm run build

RUN npm install --production && npm cache clean --force

USER node

# ------

FROM node:18-alpine as prod

WORKDIR /app
RUN apk add --no-cache libc6-compat

ENV NODE_ENV production

RUN addgroup --system --gid 1001 node || true
RUN adduser --system --uid 1001 node || true

COPY --chown=node:node --from=build /app/dist dist
COPY --chown=node:node --from=build /app/node_modules node_modules
COPY --chown=node:node --from=build /app/package.json package.json

RUN npm i -g serve

# Set Docker as non-root user
USER node

CMD ["serve", "-s", "/app/dist"]
