name: Release Frontend

on:
  push:
    tags:
      - 'web-v*'
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          version=$(echo $GITHUB_REF_NAME | grep -o [0-9]\.*)
          cd webapp/
          docker build . --tag ghcr.io/ingsw24/prisma-todos-web:$version
          docker push ghcr.io/ingsw24/prisma-todos-web:$version
